export TASK_TRACKER_SERVER_PORT=4000
export TASK_TRACKER_DB_USER=postgres
export TASK_TRACKER_DB_PASS=Admin_123
export TASK_TRACKER_DB_NAME=tasktracker
export TASK_TRACKER_DB_PORT=5432
export TASK_TRACKER_DB_HOST=localhost
# export TASK_TRACKER_SLACK_API_URL=https://slack.com/api/
# export TASK_TRACKER_SLACK_CHANNEL_ID=#task-test
# export TASK_TRACKER_SLACK_BOTUSER_TOKEN=xoxb-19899765842-845752466598-Jq54tAmaqBX53SkXeYDa5Jrp
# export TASK_TRACKER_JWT_SECRET=o0RHBDG2Id

clear
npm start
